# 🐍 Python Data Structures — Practice Worksheet
### 18 Tasks covering Numbers, Booleans, Strings, Loops, Lists, Tuples, Dictionaries, Sets, NumPy & Pandas

---

> 📌 **Instructions**
> - Complete **all 18 tasks** from top to bottom — each builds on previous concepts.
> - Fill in every `# YOUR CODE HERE` block. Do **not** change task descriptions.
> - Run each cell after completing it to verify your output.
> - Expected outputs are shown where helpful.

---


## ⚙️ Setup — Run This Cell First


In [58]:
import random
import collections
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
print("All libraries imported successfully ✅")


All libraries imported successfully ✅


---
# 🔢 Section 1 — Primitive Data Types


## 📝 Task 1 — Numbers & Arithmetic

### Background
Python supports two main numeric types: `int` (whole numbers) and `float` (decimals). You can use the standard arithmetic operators: `+`, `-`, `*`, `/`, `//` (floor division), `%` (modulo), `**` (exponentiation).

### 🎯 Your Task
Given `a = 17` and `b = 5`, compute and **print** each of the following with a descriptive label:

| Expression | Expected Output |
|---|---|
| `a + b` | 22 |
| `a - b` | 12 |
| `a * b` | 85 |
| `a / b` | 3.4 |
| `a // b` | 3 |
| `a % b` | 2 |
| `a ** b` | 1419857 |

Then print the **type** of `a` and the **type** of `a / b` and explain (in a comment) why they differ.

> 💡 **Hint:** Use `print(f"a + b = {a + b}")` for clean labelled output. Use `type()` to check types.


In [57]:
a = 17
b = 5

# YOUR CODE HERE
# Print all 7 arithmetic results with labels
print("Addition: ",(a+b))
print("Subtraction: ",(a-b))
print("Multiplication: ",(a*b))
print("Division: ",(a/b))
print("Integer Division: ",(a//b))
print("Modulus: ",(a%b))
print("Square: ",(a**b))

# Print type of a
print(type(a))

# Print type of a / b
print(type(a/b))

# Comment: why is the type of a/b different from the type of a?
# Answer: because in python a/b returns a float even if both a and b are integers but a//b returns integer division


Addition:  22
Subtraction:  12
Multiplication:  85
Division:  3.4
Integer Division:  3
Modulus:  2
Square:  1419857
<class 'int'>
<class 'float'>


## 📝 Task 2 — Boolean Logic

### Background
Python's Boolean type has two values: `True` and `False`. Logical operators are written as English words: `and`, `or`, `not`. The XOR (exclusive or) result can be checked with `!=`.

### 🎯 Your Task
Given `p = True` and `q = False`:

1. Print the result of `p and q`, `p or q`, `not p`, and `p != q`
2. Create a variable `score = 73` and write an `if / elif / else` block that prints:
   - `"Distinction"` if score ≥ 85
   - `"Merit"` if score is between 70 and 84 (inclusive)
   - `"Pass"` if score is between 50 and 69 (inclusive)
   - `"Fail"` otherwise

> 💡 **Hint:** Use `elif` for multiple conditions. The order matters — check the highest threshold first.


In [55]:
p = True
q = False

# YOUR CODE HERE — Part 1: Boolean operations
print("p and q", p and q)
print("p or q", p or q)
print("not p", not p)
print("p!=q", p!=q)
# YOUR CODE HERE — Part 2: Grade classifier
score = 73

if(score>=85):
    print("Distinction")

elif(score>=70 and score<=84):
    print("Merit")

elif(score>=50 and score<=69):
    print("Pass")

else:
    print("Fail")


p and q False
p or q True
not p False
p!=q True
Merit


## 📝 Task 3 — String Operations

### Background
Strings in Python are sequences of characters. Useful built-in string methods include `.upper()`, `.lower()`, `.replace()`, `.split()`, `.strip()`, and `.count()`. You can also use `len()`, slicing `[start:end]`, and f-strings for formatting.

### 🎯 Your Task
Work with the sentence below and complete all five operations:

```python
sentence = "  Python is a powerful programming language  "
```

| # | Operation | Expected Result |
|---|-----------|-----------------|
| 1 | Strip whitespace | `"Python is a powerful programming language"` |
| 2 | Convert to UPPERCASE | `"PYTHON IS A POWERFUL PROGRAMMING LANGUAGE"` |
| 3 | Count the word `"a"` (exact, case-sensitive) | `1` |
| 4 | Replace `"powerful"` with `"versatile"` | `"Python is a versatile programming language"` |
| 5 | Split into a list of words | `['Python', 'is', 'a', 'versatile', ...]` |

Finally, use an **f-string** to print: `"The sentence has X words."` (where X is the actual count).

> 💡 **Hint:** Chain methods: `sentence.strip().upper()`. Use `.split()` with no arguments to split on any whitespace.


In [54]:
sentence = "  Python is a powerful programming language  "

# YOUR CODE HERE
# 1. Strip whitespace and save to 'clean'
clean=sentence.strip()
print(clean)
# 2. Print UPPERCASE version
print(clean.upper())

# 3. Count occurrences of the word "a"
print("Occurences of word a: ", clean.count("a"))

# 4. Replace "powerful" with "versatile" and save to 'new_sentence'
new_sentence=clean.replace("powerful", "versatile")
print(new_sentence)

# 5. Split new_sentence into a list of words
new_sentence=new_sentence.split()

# Print: "The sentence has X words."
print("The sentence has", len(new_sentence), "words")

Python is a powerful programming language
PYTHON IS A POWERFUL PROGRAMMING LANGUAGE
Occurences of word a:  4
Python is a versatile programming language
The sentence has 6 words


## 📝 Task 4 — Loops & Conditionals

### Background
`for` loops iterate over a sequence. `while` loops run as long as a condition is `True`. Use `break` to exit early and `continue` to skip to the next iteration.

### 🎯 Your Task

**Part A:** Use a `for` loop with `range()` to print all **even numbers from 1 to 30** on a single line separated by spaces.

**Part B:** Use a `while` loop to compute the **sum of all odd numbers from 1 to 99** (i.e., 1 + 3 + 5 + … + 99). Print the result.
> Expected answer: 2500

**Part C:** Use a `for` loop over `range(1, 21)`. Print the number normally, **but**:
- If divisible by both 3 and 5 → print `"FizzBuzz"`
- If divisible by 3 only → print `"Fizz"`
- If divisible by 5 only → print `"Buzz"`

> 💡 **Hint for Part A:** Use `print(n, end=' ')` to stay on the same line, or build a list and use `' '.join(...)`.  
> 💡 **Hint for Part C:** Check the combined condition (`% 3 == 0 and % 5 == 0`) **first** before the individual ones.


In [53]:
# Part A: Even numbers from 1 to 30
# YOUR CODE HERE
for i in range(1, 31):
    if(i%2==0):
        print(i,end=" ")

# Part B: Sum of odd numbers from 1 to 99
# YOUR CODE HERE
i=1
total=0

while(i<100):
    if(i%2!=0):
        total+=i
    i+=1
print("\nsum of odd numbers from 1 to 99: ",total)
        

# Part C: FizzBuzz from 1 to 20
# YOUR CODE HERE
for i in range(1, 21):
    if(i%3==0):
        print(i,": Fizz")
    elif(i%5==0):
        print(i,": Buzz")
    elif(i%3==0 and i%5==0):
        print(i,": FizzBuzz")

2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 
sum of odd numbers from 1 to 99:  2500
3 : Fizz
5 : Buzz
6 : Fizz
9 : Fizz
10 : Buzz
12 : Fizz
15 : Fizz
18 : Fizz
20 : Buzz


---
# 📋 Section 2 — Lists


## 📝 Task 5 — List Basics: Create, Access, Modify

### Background
A Python list is **mutable** and **ordered**. Elements are accessed by zero-based index. Negative indices count from the end (`-1` is the last element). Common methods: `.append()`, `.insert()`, `.remove()`, `.pop()`, `.sort()`, `.reverse()`.

### 🎯 Your Task
Start with:
```python
fruits = ["mango", "banana", "apple", "cherry", "orange"]
```

Perform the following operations **in order**, printing the list after each step:

1. Print the **first** and **last** element using positive and negative indexing.
2. **Append** `"grape"` to the end.
3. **Insert** `"kiwi"` at index 2.
4. **Remove** `"banana"` from the list.
5. **Pop** the element at index 0 and print what was removed.
6. **Sort** the list alphabetically and print it.
7. **Reverse** the sorted list and print it.

> 💡 **Hint:** Remember that `.pop(index)` returns the removed element, so you can capture it: `removed = fruits.pop(0)`.


In [44]:
fruits = ["mango", "banana", "apple", "cherry", "orange"]

# YOUR CODE HERE
# 1. Print first and last elements
print("First element: ",fruits[0])
print("Last element: ",fruits[-1])
# 2. Append "grape"
fruits.append("grape")
print(fruits)

# 3. Insert "kiwi" at index 2
fruits.insert(2,"kiwi")
print(fruits)
# 4. Remove "banana"
fruits.remove("banana")
print(fruits)
# 5. Pop element at index 0, print what was removed
fruits=fruits[::-1]
removed_fruit=fruits.pop()
print("Popped element: ",removed_fruit)
fruits=fruits[::-1]

# 6. Sort alphabetically
fruits.sort()
print("Sorteed list: ",fruits)
# 7. Reverse the list
fruits=fruits[::-1]
print("Reversed list: ",fruits)

First element:  mango
Last element:  orange
['mango', 'banana', 'apple', 'cherry', 'orange', 'grape']
['mango', 'banana', 'kiwi', 'apple', 'cherry', 'orange', 'grape']
['mango', 'kiwi', 'apple', 'cherry', 'orange', 'grape']
Popped element:  mango
Sorteed list:  ['apple', 'cherry', 'grape', 'kiwi', 'orange']
Reversed list:  ['orange', 'kiwi', 'grape', 'cherry', 'apple']


## 📝 Task 6 — List Slicing

### Background
Slicing extracts a **sub-list** using the syntax `list[start:stop:step]`:
- `start` is inclusive, `stop` is exclusive
- A negative `step` reverses the direction
- Omitting `start` or `stop` defaults to the beginning or end

### 🎯 Your Task
Work with:
```python
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

| # | Slice | Expected Result |
|---|-------|-----------------|
| 1 | First 4 elements | `[0, 1, 2, 3]` |
| 2 | Last 3 elements | `[7, 8, 9]` |
| 3 | Elements from index 2 to 7 | `[2, 3, 4, 5, 6]` |
| 4 | Every second element | `[0, 2, 4, 6, 8]` |
| 5 | The entire list **reversed** | `[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]` |
| 6 | Last 5 elements **reversed** | `[9, 8, 7, 6, 5]` |

> 💡 **Hint:** To reverse use `[::-1]`. For last N items use `[-N:]`. To reverse a slice: `numbers[4:9][::-1]` reverses a sub-section.


In [43]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# YOUR CODE HERE
# 1. First 4 elements
print(numbers[:4])

# 2. Last 3 elements
print(numbers[-1:-4:-1])

# 3. Index 2 to 7 (not including 7)
print(numbers[2:8])

# 4. Every second element


# 5. Entire list reversed
print(numbers[::-1])

# 6. Last 5 elements reversed
first_five_numbers=numbers[0:5]
last_five_numbers=numbers[-1:-6:-1]
new_list=first_five_numbers+(last_five_numbers)
print(numbers)

[0, 1, 2, 3]
[9, 8, 7]
[2, 3, 4, 5, 6, 7]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## 📝 Task 7 — List Comprehensions

### Background
List comprehensions are a concise way to create lists:
```python
[expression for item in iterable if condition]
```
They replace many `for` loops with a single readable line.

### 🎯 Your Task
Use **list comprehensions** (no regular for-loops!) to create and print each of the following:

1. A list of the **squares** of numbers 1 through 15: `[1, 4, 9, 16, ...]`
2. A list of numbers from 1–50 that are **divisible by 3 or 5** (but not both): `[3, 5, 6, 9, 10, ...]`
3. A list of the **lengths** of each word in the sentence `"the quick brown fox jumps over the lazy dog"`
4. A list of **uppercase versions** of only the words that have **5 or more letters**: `['QUICK', 'BROWN', 'JUMPS', 'LAZY']` *(hint: 'over' has 4, skip it)*

> 💡 **Hint for #2:** `(n % 3 == 0) != (n % 5 == 0)` is Python's way to express XOR for two conditions.  
> 💡 **Hint for #3:** `sentence.split()` gives you the word list.


In [42]:
# 1. Squares of 1 to 15
# YOUR CODE HERE
result=[n**n for n in range(1, 16)]
print(result)

# 2. Numbers 1-50 divisible by 3 OR 5 but NOT both
# YOUR CODE HERE
result=[n for n in range(1, 51) if(n%3==0 or n%5==0 and not(n%5==0 and n%3==0))]
print(result)
# 3. Lengths of each word in the sentence
sentence = "the quick brown fox jumps over the lazy dog"
# YOUR CODE HERE
lengths=[(word, len(word)) for word in sentence.split()]
print(lengths)

# 4. Uppercase words with 5 or more letters
# YOUR CODE HERE
words=[w for w in sentence.split() if(len(w)>=5)]
print(words)

[1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000, 285311670611, 8916100448256, 302875106592253, 11112006825558016, 437893890380859375]
[3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50]
[('the', 3), ('quick', 5), ('brown', 5), ('fox', 3), ('jumps', 5), ('over', 4), ('the', 3), ('lazy', 4), ('dog', 3)]
['quick', 'brown', 'jumps']


## 📝 Task 8 — Nested Lists & the `collections.Counter`

### Background
A **list of lists** creates a 2D (matrix-like) structure. Access elements with `matrix[row][col]`.  
`collections.Counter` is a dictionary subclass that counts how many times each element appears in an iterable.

### 🎯 Your Task

**Part A — Nested List:**  
Create the following 3×3 matrix as a list of lists and then:
```
matrix = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]
```
- Print the **second row** (index 1)
- Print the **element at row 2, column 1** (value: 8)
- Use a nested list comprehension to create a **transposed** version (rows become columns)
  - Expected: `[[1, 4, 7], [2, 5, 8], [3, 6, 9]]`

**Part B — Counter:**  
Generate a list of 300 random integers between 1 and 10 (inclusive), then:
- Use `collections.Counter` to count each number
- Print the **3 most common** numbers and their counts
- Print the **least common** number

> 💡 **Hint for transpose:** `[[matrix[r][c] for r in range(3)] for c in range(3)]`  
> 💡 **Hint for Counter:** `counter.most_common(3)` returns the top 3 as a list of `(value, count)` tuples.


In [41]:
import collections, random

# Part A — Nested list
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

# YOUR CODE HERE
# Print second row
print(matrix[1])

# Print element at row 2, col 1
print(matrix[1][0])

# Transpose using nested list comprehension
transpose = [[matrix[r][c] for r in range(len(matrix))] for c in range(len(matrix[0]))]
print(transpose)

# Part B — Counter
random.seed(42)
# YOUR CODE HERE
# Generate 300 random integers between 1 and 10
random_integers=[random.randint(1, 10) for _ in range(1, 301)]
print(random_integers)

# Count with Counter
count_total=collections.Counter(random_integers)
print("Count with counter: ",count_total)

# Print top 3 most common
print("Printing most common")
most_common_integers=count_total.most_common(3) 
print(most_common_integers)

# Print least common
print("Printing least common")
least_common = sorted(count_total.items(), key=lambda x: x[1])
for i in range(3):
    print(least_common[i])

[4, 5, 6]
4
[[1, 4, 7], [2, 5, 8], [3, 6, 9]]
[2, 1, 5, 4, 4, 3, 2, 9, 2, 10, 7, 1, 1, 2, 4, 4, 9, 10, 1, 9, 4, 9, 7, 4, 8, 10, 5, 1, 3, 7, 6, 5, 3, 4, 6, 2, 2, 7, 2, 6, 6, 10, 5, 1, 8, 9, 2, 7, 2, 9, 5, 10, 6, 10, 4, 2, 1, 4, 5, 2, 4, 2, 7, 5, 8, 6, 3, 6, 6, 4, 5, 2, 10, 3, 9, 4, 3, 8, 7, 5, 9, 4, 6, 1, 4, 1, 6, 7, 5, 2, 4, 10, 6, 4, 8, 7, 8, 3, 5, 3, 4, 9, 9, 5, 10, 7, 10, 7, 6, 4, 3, 9, 8, 2, 1, 2, 3, 3, 7, 10, 2, 7, 7, 10, 8, 9, 5, 9, 1, 2, 9, 5, 6, 2, 5, 7, 3, 8, 1, 5, 9, 3, 9, 2, 5, 9, 10, 4, 3, 6, 3, 9, 9, 1, 10, 6, 8, 1, 2, 6, 5, 4, 1, 4, 10, 2, 2, 8, 2, 9, 3, 3, 8, 9, 3, 5, 9, 10, 7, 4, 9, 4, 5, 7, 6, 8, 9, 8, 2, 4, 4, 2, 6, 1, 10, 9, 4, 10, 4, 1, 2, 1, 4, 2, 1, 6, 2, 9, 4, 5, 8, 4, 9, 3, 10, 10, 8, 4, 8, 7, 4, 2, 2, 7, 6, 7, 7, 8, 1, 2, 1, 7, 6, 2, 4, 4, 4, 9, 8, 3, 7, 3, 5, 8, 4, 2, 8, 9, 2, 1, 9, 1, 2, 4, 3, 7, 8, 8, 4, 7, 1, 3, 7, 1, 7, 5, 8, 5, 7, 9, 8, 3, 4, 5, 4, 1, 10, 9, 1, 6, 1, 1, 10, 8, 9, 9, 3, 1, 9, 2, 3, 2, 10, 2, 4, 7, 2, 10, 4, 10]
Count with counter:  Counter

---
# 🔒 Section 3 — Tuples


## 📝 Task 9 — Tuples: Immutability & Practical Uses

### Background
Tuples look like lists but use `()` instead of `[]`. They are **immutable** — you cannot add, remove, or change elements after creation. This makes them useful for fixed data like coordinates, RGB colours, or records. Tuples support indexing, slicing, and iteration just like lists.

### 🎯 Your Task

**Part A — Basic Tuple Operations:**
```python
student = ("Alice", 22, "Computer Science", 3.8)
```
- Print the student's name (index 0) and GPA (index 3)
- Try to change the name to `"Bob"` — catch the resulting `TypeError` with a `try/except` block and print `"Tuples are immutable!"`
- Unpack the tuple into 4 separate variables: `name, age, major, gpa` and print each

**Part B — List of Tuples:**  
You have coordinates of 5 cities:
```python
cities = [("Karachi", 24.86, 67.01),
          ("Lahore",  31.55, 74.35),
          ("Islamabad", 33.72, 73.06),
          ("Peshawar", 34.01, 71.57),
          ("Quetta",  30.18, 66.99)]
```
- Loop over the list and print each city in the format: `"City: Karachi | Lat: 24.86 | Lon: 67.01"`
- Sort the cities by **latitude** (ascending) and print the sorted list

> 💡 **Hint for sorting:** `sorted(cities, key=lambda c: c[1])` sorts by the second element of each tuple.


In [40]:
# Part A
student = ("Alice", 22, "Computer Science", 3.8)

# YOUR CODE HERE
# Print name and GPA
print("Name: ",student[0],"\tGPA: ",student[3])

# Try to change name — catch TypeError
try:
    student[0]="Umer"

except TypeError:
    print("Name cannot be changed")

# Unpack into 4 variables and print each
name=student[0]
age=student[1]
department=student[2]
cgpa=student[3]

# Part B
cities = [("Karachi",   24.86, 67.01),
          ("Lahore",    31.55, 74.35),
          ("Islamabad", 33.72, 73.06),
          ("Peshawar",  34.01, 71.57),
          ("Quetta",    30.18, 66.99)]

# YOUR CODE HERE
# Loop and print each city's info
for name,lat,lon in cities:
    print(name, lat, lon)

# Sort by latitude and print
cities.sort()
print(cities)

Name:  Alice 	GPA:  3.8
Name cannot be changed
Karachi 24.86 67.01
Lahore 31.55 74.35
Islamabad 33.72 73.06
Peshawar 34.01 71.57
Quetta 30.18 66.99
[('Islamabad', 33.72, 73.06), ('Karachi', 24.86, 67.01), ('Lahore', 31.55, 74.35), ('Peshawar', 34.01, 71.57), ('Quetta', 30.18, 66.99)]


---
# 📖 Section 4 — Dictionaries


## 📝 Task 10 — Dictionary Basics: Create, Access, Update

### Background
A dictionary stores data as **key → value** pairs. Keys must be unique and immutable (strings, numbers, tuples). Values can be anything. Key methods: `.keys()`, `.values()`, `.items()`, `.get()`, `.update()`, `.pop()`.

### 🎯 Your Task
Start with this student record:
```python
student = {
    "name": "Sara",
    "age": 20,
    "courses": ["Math", "Physics", "CS"],
    "grades": {"Math": 88, "Physics": 75, "CS": 92}
}
```

1. Print Sara's **name** and **age**
2. Print her **list of courses**
3. Print her **CS grade** (access the nested dictionary)
4. Add a new key `"year"` with value `2`
5. Update her **age** to `21`
6. Remove the `"Physics"` grade from the nested `"grades"` dictionary using `.pop()`
7. Loop over all key-value pairs with `.items()` and print them line by line
8. Print a list of all **keys** and a list of all **values**

> 💡 **Hint:** Access nested dicts with chained brackets: `student["grades"]["CS"]`  
> 💡 **Hint:** `student.get("email", "Not found")` returns a default value if the key doesn't exist.


In [39]:
student = {
    "name": "Sara",
    "age": 20,
    "courses": ["Math", "Physics", "CS"],
    "grades": {"Math": 88, "Physics": 75, "CS": 92}
}

# YOUR CODE HERE
# 1. Print name and age
print("name: ",student["name"])
print("age: ",student["age"])

# 2. Print list of courses
print(student["courses"])

# 3. Print CS grade (nested access)
print(student["grades"]["CS"])

# 4. Add "year": 2
student["year"]=2

# 5. Update age to 21
student["age"]=21

# 6. Remove "Physics" from grades using .pop()
print(student["courses"].pop())

# 7. Loop and print all key-value pairs
for key, value in student.items():
    print(key, ": ", value)

# 8. Print list of keys and list of values
print("keys: ",student.keys())
print("values: ",student.values())

name:  Sara
age:  20
['Math', 'Physics', 'CS']
92
CS
name :  Sara
age :  21
courses :  ['Math', 'Physics']
grades :  {'Math': 88, 'Physics': 75, 'CS': 92}
year :  2
keys:  dict_keys(['name', 'age', 'courses', 'grades', 'year'])
values:  dict_values(['Sara', 21, ['Math', 'Physics'], {'Math': 88, 'Physics': 75, 'CS': 92}, 2])


## 📝 Task 11 — Dictionary Comprehension & Word Frequency Counter

### Background
Just like list comprehensions, you can build dictionaries in one line:
```python
{key_expr: value_expr for item in iterable if condition}
```
Dictionaries are perfect for counting frequencies — a pattern you'll use constantly in data science.

### 🎯 Your Task

**Part A — Dictionary Comprehension:**
1. Create a dictionary mapping each number 1–10 to its **cube**: `{1: 1, 2: 8, 3: 27, ...}`
2. Create a dictionary mapping each number 1–20 to `"even"` or `"odd"`: `{1: 'odd', 2: 'even', ...}`

**Part B — Word Frequency Counter:**  
Count how many times each word appears in the text below, ignoring case. Print the result sorted by **frequency (descending)**.

```python
text = "to be or not to be that is the question to be is to think"
```
Expected top entries: `to: 4, be: 3, is: 2, ...`

> 💡 **Hint for Part B:** Start with `freq = {}`, then loop over `text.lower().split()`.  
> Use `freq[word] = freq.get(word, 0) + 1` to safely increment counts.  
> Sort with `sorted(freq.items(), key=lambda x: x[1], reverse=True)`.


In [38]:
# Part A — Dictionary comprehensions
# 1. Cubes of 1 to 10
# YOUR CODE HERE
cubes = {i: i**3 for i in range(1, 11)}
print("Cubes from 1 to 10:", cubes)

# 2. Even/Odd mapping for 1 to 20
# YOUR CODE HERE
even_odd = {i: ("Even" if i % 2 == 0 else "Odd") for i in range(1, 21)}
print("Even/Odd mapping:", even_odd)

# Part B — Word frequency counter
text = "to be or not to be that is the question to be is to think"
# YOUR CODE HERE
words = text.split()

word_freq = {word: words.count(word) for word in set(words)}
print("Word frequencies:", word_freq)

Cubes from 1 to 10: {1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}
Even/Odd mapping: {1: 'Odd', 2: 'Even', 3: 'Odd', 4: 'Even', 5: 'Odd', 6: 'Even', 7: 'Odd', 8: 'Even', 9: 'Odd', 10: 'Even', 11: 'Odd', 12: 'Even', 13: 'Odd', 14: 'Even', 15: 'Odd', 16: 'Even', 17: 'Odd', 18: 'Even', 19: 'Odd', 20: 'Even'}
Word frequencies: {'think': 1, 'not': 1, 'be': 3, 'or': 1, 'to': 4, 'that': 1, 'the': 1, 'is': 2, 'question': 1}


---
# 🔵 Section 5 — Sets


## 📝 Task 12 — Set Operations

### Background
A **set** is an **unordered collection of unique elements**. Duplicate values are automatically removed. Sets support mathematical operations: union (`|`), intersection (`&`), difference (`-`), symmetric difference (`^`).

| Operation | Symbol | Method | Meaning |
|-----------|--------|--------|---------|
| Union | `\|` | `.union()` | All elements from both sets |
| Intersection | `&` | `.intersection()` | Only elements in **both** |
| Difference | `-` | `.difference()` | Elements in A but **not** B |
| Symmetric Difference | `^` | `.symmetric_difference()` | Elements in either but **not both** |

### 🎯 Your Task
```python
python_students = {"Alice", "Bob", "Carol", "David", "Eve"}
java_students   = {"Bob", "David", "Frank", "Grace", "Alice"}
```

1. Find students enrolled in **both** courses (intersection)
2. Find students enrolled in **at least one** course (union)
3. Find students taking **Python but NOT Java** (difference)
4. Find students taking **exactly one** course (symmetric difference)
5. Check if `{"Bob", "Alice"}` is a **subset** of `python_students`
6. Add `"Henry"` to `python_students` and remove `"Carol"` from it
7. Create a list `[1, 2, 2, 3, 3, 3, 4, 4, 4, 4]` and use a set to print only the **unique values**

> 💡 **Hint:** Use `.issubset()` or the `<=` operator for subset check.


In [37]:
python_students = {"Alice", "Bob", "Carol", "David", "Eve"}
java_students   = {"Bob", "David", "Frank", "Grace", "Alice"}

# YOUR CODE HERE
# 1. Intersection
intersection_dict=python_students.intersection(java_students)
print(intersection_dict)
# 2. Union
union_dict=python_students.union(java_students)
print(union_dict)

# 3. Difference (Python but NOT Java)
difference_dict=python_students.difference(java_students)
print(difference_dict)

# 4. Symmetric difference
sym_dif=python_students.symmetric_difference(java_students)
print(sym_dif)
# 5. Subset check: {"Bob", "Alice"} ⊆ python_students
if({"Bob", "Alice"}.issubset(python_students)):
    print("Is subset")
else:
    print("Is not subset")

# 6. Add "Henry", remove "Carol"
python_students.remove("Carol")
python_students.add("Henry")
print(python_students)

# 7. Unique values from list
nums = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
nums=set(nums)
print(nums)

{'Bob', 'Alice', 'David'}
{'Alice', 'Grace', 'Eve', 'Frank', 'Bob', 'Carol', 'David'}
{'Eve', 'Carol'}
{'Frank', 'Eve', 'Carol', 'Grace'}
Is subset
{'Eve', 'Alice', 'Bob', 'Henry', 'David'}
{1, 2, 3, 4}


---
# 🔢 Section 6 — NumPy Arrays


## 📝 Task 13 — Creating & Inspecting NumPy Arrays

### Background
NumPy arrays are **fixed-type, multi-dimensional** arrays that support fast vectorised operations. Unlike Python lists, every element must be the same type. Key creation functions: `np.array()`, `np.arange()`, `np.linspace()`, `np.zeros()`, `np.ones()`, `np.eye()`, `np.random.random()`.

### 🎯 Your Task

Create each of the following arrays and print both the array and its `.shape` and `.dtype`:

| # | Function | Parameters | Expected shape |
|---|----------|------------|----------------|
| 1 | `np.arange` | 0 to 20, step 2 | `(11,)` |
| 2 | `np.linspace` | 0 to 1, 6 evenly spaced points | `(6,)` |
| 3 | `np.zeros` | 3 rows × 4 columns | `(3, 4)` |
| 4 | `np.ones` | 2 rows × 5 columns, dtype `int16` | `(2, 5)` |
| 5 | `np.eye` | 4×4 identity matrix | `(4, 4)` |
| 6 | `np.random.randint` | values 1–100, shape 3×3 | `(3, 3)` |

> 💡 **Hint:** `np.ones((2,5), dtype='int16')` creates an integer array of ones.  
> `np.random.randint(low, high, size=(r,c))` creates random integer arrays.


In [36]:
import numpy as np

# YOUR CODE HERE
# 1. arange: 0 to 20 step 2
array_one=np.arange(0, 20, 2)
print(array_one)

# 2. linspace: 0 to 1 with 6 points
array_two=np.linspace(0, 1, 6)
print(array_two)

# 3. zeros: 3x4
zero_array=np.zeros(12)
print(zero_array.reshape(3, 4))

# 4. ones: 2x5 dtype int16
print(np.ones((2, 5), dtype=np.int16))

# 5. eye: 4x4 identity
np.eye(4)

# 6. random integers 1-100, shape 3x3
num=np.random.randint(1, 100, 9)
num.reshape(3,3)
print(num)

[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.2 0.4 0.6 0.8 1. ]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[76  9 94 65 57 48  5 84 61]


## 📝 Task 14 — Array Indexing, Slicing & Reshaping

### Background
NumPy arrays use **row, column** indexing: `A[row, col]` or `A[row][col]`.  
Slicing: `A[r1:r2, c1:c2]` extracts a sub-array.  
`.reshape(rows, cols)` changes the shape without changing the data.  
`.T` gives the transpose.

### 🎯 Your Task
```python
A = np.arange(1, 26).reshape(5, 5)
```
This creates:
```
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
```

1. Print the **element at row 2, column 3** (value: 14)
2. Print the **entire third row** (index 2): `[11 12 13 14 15]`
3. Print the **entire second column** (index 1): `[ 2  7 12 17 22]`
4. Extract the **top-left 3×3 sub-matrix**: rows 0–2, columns 0–2
5. Extract the **bottom-right 2×2 sub-matrix**: last 2 rows and last 2 cols
6. Print the **transpose** of A (shape should become `(5,5)` but rows/cols swapped)
7. Reshape A into a 1D array of 25 elements, then into a shape `(25, 1)` column vector

> 💡 **Hint:** `A[:3, :3]` extracts the top-left corner. `A[-2:, -2:]` grabs the bottom-right corner.


In [20]:
import numpy as np

A = np.arange(1, 26).reshape(5, 5)
print("Original matrix A:")
print(A)
print()

# YOUR CODE HERE
# 1. Element at row 2, col 3
print(A[1][2])

# 2. Entire third row (index 2)
print(A[2])

# 3. Entire second column (index 1)
print(A[:,1])

# 4. Top-left 3x3 sub-matrix
sub_matrix=A[0:3, 0:3]
print(sub_matrix)

# 5. Bottom-right 2x2 sub-matrix
bottom_matrix=A[3:, 3:,]
print(bottom_matrix)

# 6. Transpose
transpose_matrix=np.transpose(A)
print(transpose_matrix)

# 7. Reshape to 1D (25,) then to column vector (25,1)
reshaped=A.reshape(-1)
print(reshaped)
column_vector=A.reshape(-1, 1)
print(column_vector)

Original matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

8
[11 12 13 14 15]
[ 2  7 12 17 22]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[19 20]
 [24 25]]
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]]


## 📝 Task 15 — Vectorised Operations & Broadcasting

### Background
NumPy operations are applied **element-wise** to entire arrays without writing loops — this is called **vectorisation**. When arrays have compatible shapes, NumPy can **broadcast** smaller arrays across larger ones automatically.

### 🎯 Your Task

**Part A — Element-wise Operations:**
```python
a = np.array([10, 20, 30, 40, 50])
b = np.array([ 1,  2,  3,  4,  5])
```
Compute and print (without loops):
1. `a + b`, `a - b`, `a * b`, `a / b`
2. Square root of `a` (use `np.sqrt`)
3. All elements of `a` greater than 25 (Boolean mask)
4. Use the Boolean mask to extract only elements of `a` greater than 25

**Part B — Matrix Operations:**
```python
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])
```
5. Element-wise multiplication `M * N`
6. Matrix (dot) product `M @ N` or `np.dot(M, N)`
7. Sum of all elements, sum along each row, sum along each column

> 💡 **Hint for Boolean masking:** `mask = a > 25` creates `[False False False True True]`. Then `a[mask]` extracts `[40 50]`.  
> 💡 **Hint for axis sums:** `M.sum(axis=1)` sums each row; `M.sum(axis=0)` sums each column.


In [35]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([ 1,  2,  3,  4,  5])

# Part A
# YOUR CODE HERE
# 1. Element-wise +, -, *, /
print("addition: ",(a+b))
print("subtraction: ",(a-b))
print("multiplication: ",(a*b))
print("division: ",(a/b))

# 2. Square root of a
print(np.sqrt(a))

# 3. Boolean mask: elements of a > 25
mask=a>25
print(mask)

# 4. Extract elements > 25 using mask
mask_elements=a[mask]
print(mask_elements)

# Part B
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])

# YOUR CODE HERE
# 5. Element-wise multiplication
print(a*b)

# 6. Matrix dot product
dot_product=np.dot(a,b)
print(dot_product)

# 7. Total sum, row sums, column sums
dot_product = dot_product.reshape(1, -1)
total_sum=np.sum(dot_product)
print("Total sum: ", total_sum)
rows_sum=np.sum(dot_product, axis=1)
print("Row sum: ", rows_sum)
columns_sum=np.sum(dot_product, axis=0)
print("Columns sum: ", columns_sum)

addition:  [11 22 33 44 55]
subtraction:  [ 9 18 27 36 45]
multiplication:  [ 10  40  90 160 250]
division:  [10. 10. 10. 10. 10.]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[False False  True  True  True]
[30 40 50]
[ 10  40  90 160 250]
550
Total sum:  550
Row sum:  [550]
Columns sum:  [550]


---
# 🐼 Section 7 — Pandas DataFrames


## 📝 Task 16 — Creating & Exploring a DataFrame

### Background
A **DataFrame** is a 2D table with labelled rows (index) and columns. You can create one from a dictionary, a list of lists, a CSV file, or from scikit-learn datasets. Essential inspection methods: `.head()`, `.tail()`, `.info()`, `.describe()`, `.shape`, `.columns`, `.dtypes`, `.isnull().sum()`.

### 🎯 Your Task

**Part A — Create from a dictionary:**
```python
data = {
    "Name":    ["Ali", "Sara", "John", "Fatima", "Chris"],
    "Age":     [23, 21, 25, 22, 24],
    "Score":   [88, 92, 78, 95, 83],
    "Passed":  [True, True, True, True, True],
    "City":    ["Lahore", "Karachi", "London", "Islamabad", "New York"]
}
```
1. Create a DataFrame from this dictionary
2. Print its **shape**, **column names**, and **data types**
3. Print the **first 3 rows** and the **last 2 rows**
4. Print **summary statistics** using `.describe()`

**Part B — Load the Iris dataset:**
5. Load the Iris dataset using `load_iris()` and add the species names
6. Print **how many rows belong to each species** using `.value_counts()`
7. Print the **mean of each numerical column grouped by species**

> 💡 **Hint for Iris:** `iris_df['species'] = iris.target_names[iris.target]` maps integer targets to names.  
> 💡 **Hint for groupby:** `iris_df.groupby('species').mean(numeric_only=True)`


In [34]:
import pandas as pd
from sklearn.datasets import load_iris

# Part A
data = {
    "Name":   ["Ali", "Sara", "John", "Fatima", "Chris"],
    "Age":    [23, 21, 25, 22, 24],
    "Score":  [88, 92, 78, 95, 83],
    "Passed": [True, True, True, True, True],
    "City":   ["Lahore", "Karachi", "London", "Islamabad", "New York"]
}

# YOUR CODE HERE
# 1. Create DataFrame
dataframe=pd.DataFrame(data)

# 2. Print shape, columns, dtypes
print(dataframe.shape)
print(dataframe.columns)
print(dataframe.dtypes)

# 3. Head(3) and tail(2)
print(dataframe.head(3))
print(dataframe.tail(2))

# 4. Describe
print(dataframe.describe)

# Part B — Iris
# YOUR CODE HERE
# 5. Load iris and create DataFrame
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target]


# 6. Value counts per species
print(iris_df["species"].value_counts())

# 7. Mean per species
print(iris_df.groupby(["species"]).mean())

(5, 5)
Index(['Name', 'Age', 'Score', 'Passed', 'City'], dtype='object')
Name      object
Age        int64
Score      int64
Passed      bool
City      object
dtype: object
   Name  Age  Score  Passed     City
0   Ali   23     88    True   Lahore
1  Sara   21     92    True  Karachi
2  John   25     78    True   London
     Name  Age  Score  Passed       City
3  Fatima   22     95    True  Islamabad
4   Chris   24     83    True   New York
<bound method NDFrame.describe of      Name  Age  Score  Passed       City
0     Ali   23     88    True     Lahore
1    Sara   21     92    True    Karachi
2    John   25     78    True     London
3  Fatima   22     95    True  Islamabad
4   Chris   24     83    True   New York>
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64
            sepal length (cm)  sepal width (cm)  petal length (cm)  \
species                                                              
setosa                  5.006             3.428    

## 📝 Task 17 — Selecting, Filtering & Adding Columns

### Background
- **Select columns:** `df['col']` (Series) or `df[['col1','col2']]` (DataFrame)
- **Select rows by position:** `df.iloc[start:stop]`
- **Select rows by label/condition:** `df.loc[condition]`
- **Add a column:** `df['new_col'] = expression`
- **Multiple conditions:** Use `&` (AND) or `|` (OR) — wrap each condition in `()`

### 🎯 Your Task
Use the **Iris DataFrame** from Task 16.

1. Select and print only the `sepal length (cm)` and `petal length (cm)` columns (first 5 rows)
2. Select rows **50 through 54** using `.iloc`
3. Filter rows where `species == 'versicolor'` and print how many there are
4. Filter rows where `petal length (cm) > 5.0` **AND** `species == 'virginica'`
5. Add a new column `"petal_area"` = `petal length (cm)` × `petal width (cm)` and print the first 5 rows
6. Sort the DataFrame by `petal_area` in **descending** order and print the top 5 rows

> 💡 **Hint:** `df[(df['col1'] > val) & (df['col2'] == 'label')]` — always wrap each condition in `()`.  
> 💡 **Hint:** `df.sort_values('petal_area', ascending=False).head(5)`


In [30]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target]

# YOUR CODE HERE
# 1. Select sepal length and petal length columns (head 5)
print(iris_df[["sepal length (cm)", "petal length (cm)"]].head())

# 2. Rows 50 through 54 using iloc
print(iris_df.iloc[50:54])

# 3. Filter versicolor species, print count
print((iris_df["species"] == "versicolor").sum())


# 4. Filter: petal length > 5.0 AND species == 'virginica'
print(
    "Filter: petal length > 5.0 AND species == 'virginica': ",
    ((iris_df["petal length (cm)"] > 5.0) & (iris_df["species"] == "virginica")).sum()
)

# 5. Add petal_area column, print head
# Create new column
iris_df["petal_area"] = iris_df["petal length (cm)"] * iris_df["petal width (cm)"]

# Print the full column (optional)
print(iris_df["petal_area"])

# Print first 5 rows
print(iris_df["petal_area"].head())

# 6. Sort by petal_area descending, top 5
petal_area_des=iris_df["petal_area"].sort_values(ascending=False)
print(petal_area_des.head())


   sepal length (cm)  petal length (cm)
0                5.1                1.4
1                4.9                1.4
2                4.7                1.3
3                4.6                1.5
4                5.0                1.4
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   

       species  
50  versicolor  
51  versicolor  
52  versicolor  
53  versicolor  
50
Filter: petal length > 5.0 AND species == 'virginica':  41
0       0.28
1       0.28
2       0.26
3       0.30
4       0.28
       ...  
145    11.96
146     9.50
147    10.40
148    12.42
149     9.18
Name: petal_area, Length: 150, dtype: float64
0    0.28
1    0.28
2  

## 📝 Task 18 — Capstone: Combined Data Structures Challenge

### Background
Real data science tasks require combining **all** the data structures you have learned. This final task tests your ability to choose the right structure for each job.

### 🎯 Your Task
You are given student records as a **list of dictionaries**:

```python
students = [
    {"name": "Alice",   "scores": [85, 90, 78], "city": "Lahore"},
    {"name": "Bob",     "scores": [60, 55, 70], "city": "Karachi"},
    {"name": "Carol",   "scores": [92, 88, 95], "city": "Islamabad"},
    {"name": "David",   "scores": [70, 65, 80], "city": "Lahore"},
    {"name": "Eve",     "scores": [50, 45, 55], "city": "Karachi"},
    {"name": "Frank",   "scores": [88, 92, 84], "city": "Islamabad"},
    {"name": "Grace",   "scores": [75, 80, 78], "city": "Lahore"},
]
```

Complete each of the following:

1. **Average score:** Add a key `"average"` to each student dict containing the average of their `scores` (round to 2 decimal places). Print all names and averages.

2. **Grade assignment:** Using a dictionary comprehension, create a dict `{name: grade}` where grade is:
   - `"A"` if average ≥ 85
   - `"B"` if average ≥ 70
   - `"C"` if average ≥ 55
   - `"F"` otherwise

3. **Top students:** Use a list comprehension to create a list of **names** of students with average ≥ 80.

4. **Unique cities:** Use a **set** to find all unique cities, then print them.

5. **NumPy statistics:** Convert all scores into a **2D NumPy array** (shape `7×3`). Compute and print:
   - Overall mean, min, max
   - Mean score per student (axis=1)
   - Mean score per test/column (axis=0)

6. **Pandas summary:** Create a **DataFrame** with columns `Name`, `Average`, `Grade`, `City`. Print it, then print the **average score per city** using `.groupby()`.

> 💡 **Hints:**
> - `sum(scores) / len(scores)` or `np.mean(scores)` for averages
> - `np.array([s["scores"] for s in students])` to build the 2D array
> - For the DataFrame, build a list of dicts or use parallel lists


In [33]:
import numpy as np
import pandas as pd

students = [
    {"name": "Alice",  "scores": [85, 90, 78], "city": "Lahore"},
    {"name": "Bob",    "scores": [60, 55, 70], "city": "Karachi"},
    {"name": "Carol",  "scores": [92, 88, 95], "city": "Islamabad"},
    {"name": "David",  "scores": [70, 65, 80], "city": "Lahore"},
    {"name": "Eve",    "scores": [50, 45, 55], "city": "Karachi"},
    {"name": "Frank",  "scores": [88, 92, 84], "city": "Islamabad"},
    {"name": "Grace",  "scores": [75, 80, 78], "city": "Lahore"},
]

# YOUR CODE HERE — Step 1: Add "average" key to each student dict
# Step 1: Add "average" key to each student
for student in students:
    student["average"] = sum(student["scores"]) / len(student["scores"])

# Check the result
for student in students:
    print(student)

# YOUR CODE HERE — Step 2: Dict comprehension {name: grade}
grades = {
    student["name"]: (
        "A" if student["average"] >= 90 else
        "B" if student["average"] >= 80 else
        "C" if student["average"] >= 70 else
        "D" if student["average"] >= 60 else
        "F"
    )
    for student in students
}

print(grades)

# YOUR CODE HERE — Step 3: List of names with average >= 80
grade_eighty={student["name"]: (student["average"]) for student in students}
print(grade_eighty)

# YOUR CODE HERE — Step 4: Set of unique cities
unique_cities = {student["city"] for student in students}
print(unique_cities)

# YOUR CODE HERE — Step 5: NumPy 2D array and statistics
import numpy as np

# Create a 2D NumPy array of scores
scores_array = np.array([student["scores"] for student in students])
print("Scores array:\n", scores_array)

# Compute statistics
print("\nMean per student:", np.mean(scores_array, axis=1))   # average across each row
print("Mean per test:", np.mean(scores_array, axis=0))        # average across each column
print("Min score:", np.min(scores_array))
print("Max score:", np.max(scores_array))

# YOUR CODE HERE — Step 6: Pandas DataFrame and groupby city
import pandas as pd

# Step 6a: Convert list of dicts to DataFrame
students_df = pd.DataFrame(students)
print("DataFrame:\n", students_df)

# Step 6b: Group by city and calculate statistics (mean of averages)
city_group = students_df.groupby("city")["average"].mean()
print("\nMean average score per city:\n", city_group)

{'name': 'Alice', 'scores': [85, 90, 78], 'city': 'Lahore', 'average': 84.33333333333333}
{'name': 'Bob', 'scores': [60, 55, 70], 'city': 'Karachi', 'average': 61.666666666666664}
{'name': 'Carol', 'scores': [92, 88, 95], 'city': 'Islamabad', 'average': 91.66666666666667}
{'name': 'David', 'scores': [70, 65, 80], 'city': 'Lahore', 'average': 71.66666666666667}
{'name': 'Eve', 'scores': [50, 45, 55], 'city': 'Karachi', 'average': 50.0}
{'name': 'Frank', 'scores': [88, 92, 84], 'city': 'Islamabad', 'average': 88.0}
{'name': 'Grace', 'scores': [75, 80, 78], 'city': 'Lahore', 'average': 77.66666666666667}
{'Alice': 'B', 'Bob': 'D', 'Carol': 'A', 'David': 'C', 'Eve': 'F', 'Frank': 'B', 'Grace': 'C'}
{'Alice': 84.33333333333333, 'Bob': 61.666666666666664, 'Carol': 91.66666666666667, 'David': 71.66666666666667, 'Eve': 50.0, 'Frank': 88.0, 'Grace': 77.66666666666667}
{'Karachi', 'Islamabad', 'Lahore'}
Scores array:
 [[85 90 78]
 [60 55 70]
 [92 88 95]
 [70 65 80]
 [50 45 55]
 [88 92 84]
 [75 8

---
## 🤔 Reflection Questions

Answer the following as comments in the cell below:

1. What is the key difference between a **list** and a **tuple**? When would you prefer a tuple?
2. What is the key difference between a **list** and a **set**? Give one real-world use case for each.
3. Why can't a **list** be used as a dictionary key, but a **tuple** can?
4. In Task 15, what is the advantage of NumPy **vectorisation** over using a Python `for` loop?
5. In Task 17, why do we use `&` instead of `and` when filtering a Pandas DataFrame?
6. Looking at the Capstone (Task 18), which data structure did you find most useful? Why?


In [ ]:
# Q1:
#Key difference:
#List → mutable (can change elements, add, remove).
#Tuple → immutable (cannot change once created).

#Use a tuple when:
#You want fixed data that shouldn’t change(coordinates of a point)
#You need it as a dictionary key or in a set (lists can’t be keys).
#You want slightly faster performance for read-only data.

# Q2:
# Key difference between list and set:
# List is ordered, allows duplicates, indexable
# Set is unordered, no duplicates, not indexable

# Real-world use case:
# List: shopping cart items (order matters, duplicates allowed)
# Set: unique usernames in a system (no duplicates)

# Q3:
# Lists are mutable, so their contents can change, which makes their hash value unreliable.
# Dictionary keys must be immutable and hashable.
# Tuples are immutable, so they can safely be used as dictionary keys.

# Q4:
# Advantage of NumPy vectorization over Python for loop:
# - NumPy operations are implemented in C, so they are much faster than Python loops.
# - Allows element-wise operations directly on arrays without writing explicit loops.
# - Leads to cleaner and more readable code.

# Q5:
# In Pandas, & is used for element-wise logical AND between Series (column conditions).
# Python's 'and' works on single boolean values, not arrays/Series.
# Each condition must also be enclosed in parentheses when using & or |.

# Q6:
# Most useful data structure: Pandas DataFrame
# Reason:
# - It allows tabular representation of the students data.
# - Provides easy grouping, aggregation, and filtering (e.g., groupby city, mean calculation).
# - Works seamlessly with NumPy for numerical computations.
# - Makes analysis concise and readable compared to nested lists/dicts.